language: node_js
node_js:
- "stable"
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cd vide_frigo
- mysql -e 'create database videfrigo_test;'
- mysql -u root videfrigo_test < initdb_test/init.sql
install:
- npm install --prefix ./vide_frigo/
- vide_frigo/node_modules/protractor/bin/webdriver-manager update

env:
- NODE_ENV=TEST NODE_PORT=3000 DB_SERVER_PORT=3306 MYSQL_TYPE=mysql MYSQL_HOST=localhost
  MYSQL_DATABASE=videfrigo_test MYSQL_USER=root MYSQL_PASSWORD=
mysql:
  adapter: mysql2
  username: root
  encoding: utf8
database: pgp_test


